apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  releaseName: redis
  interval: 50m
  chart:
    spec:
      chart: redis
      version: "17.11.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
  install:
    remediation:
      retries: 3
  values:
    architecture: standalone
    auth:
      enabled: true
      password: "redis-password"
    master:
      persistence:
        enabled: true
        size: 1Gi 