apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      version: "17.x"
  values:
    architecture: replication
    auth:
      enabled: true
      password: "redis-password"
    master:
      resources:
        limits:
          memory: 512Mi
          cpu: 500m
        requests:
          memory: 256Mi
          cpu: 200m
      persistence:
        size: 5Gi
    replica:
      replicaCount: 2
      resources:
        limits:
          memory: 256Mi
          cpu: 250m
        requests:
          memory: 128Mi
          cpu: 100m
      persistence:
        size: 5Gi
    metrics:
      enabled: true
    sentinel:
      enabled: true 