apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/redis
  - ../base/grafana
  - ../base/prometheus
patches:
  - path: podinfo-patch.yaml
  - path: redis-patch.yaml
  - path: grafana-patch.yaml
  - path: prometheus-patch.yaml 